from .setup import Base
from backend.models.about_app import AboutApp
from backend.models.lisences import Lisences
from backend.models.customers import Customers
from backend.models.products import Products
from backend.models.sales import Sales
from backend.models.bills import Bills
from backend.models.settings import Settings
from backend.models.accounts import Accounts
from backend.models.vendors import Vendors
from backend.models.purchase import Purchases